const projects = [
    {
        id:1,
        name:'All plastic world',
        description:'React.js SPA, created with Vite. Backend created with PostgreSQL and Sequelize ORM. Animations created with framer motion and 3D animation - created with React three fiber (three.js). CSS created with Tailwind CSS. Currently in progress.',
        photoUrl:'../../public/pictures/allplasticworld.png',
        projectCode:'https://github.com/Kost90/allplastic-world',
        projectUrl:'https://allplastic-world-29d4.vercel.app/',
        type:'react-app',
        logoUrld:'../../public/svg/react-logo.svg',
    },
    {
        id:2,
        name:'Aperture',
        description:'Landing responsive website. Created using HTML, SCSS, JavaScript.',
        photoUrl:'../../public/pictures/apertur.png',
        projectCode:'https://github.com/Kost90/aperture',
        projectUrl:'https://kost90.github.io/aperture/',
        type:'html-css',
        logoUrld:'../../public/svg/html-1.svg',
    },
    {
        id:3,
        name:'DomiLTD',
        description:'Gatsby.js website with GraphQL querys. Animations created with framer motion.',
        photoUrl:'../../public/pictures/domiltd.png',
        projectCode:'https://github.com/Kost90/domiltd',
        projectUrl:'https://domi-ltd.com/',
        type:'gatsby',
        logoUrld:'../../public/svg/gatsby.svg',
    },
    {
        id:4,
        name:'Hestiya BTI',
        description:'Full stack Next.js app with appointment Scheduling. Data saving in the MongoDB',
        photoUrl:'../../public/pictures/hestiya-bti.png',
        projectCode:'https://github.com/Kost90/BTI',
        projectUrl:'https://hestiyabti.com/',
        type:'next',
        logoUrld:'../../public/next.svg',
    },
    {
        id:5,
        name:'Hlegals',
        description:'Fist website created by myself, with jquery, slick slider and some animation libraries.',
        photoUrl:'../../public/pictures/hlegal.png',
        projectCode:'https://github.com/Kost90/Hlegal',
        projectUrl:'https://kost90.github.io/Hlegal/index.html',
        type:'html-css',
        logoUrld:'../../public/svg/html-1.svg',
    },
    {
        id:6,
        name:'DM Makeup',
        description:'Front end: Next.js app. Landing page with load more photos logic.',
        photoUrl:'../../public/pictures/makeup.png',
        projectCode:'https://github.com/Kost90/makeup-dm',
        projectUrl:'https://makeup-dm.com/',
        type:'next',
        logoUrld:'../../public/next.svg',
    },
    {
        id:7,
        name:'Map app',
        description:'React app with integrated map. You can add new object to the map, all objects are clustering. When you zoomin or zoomout tour cardlist is filtering and show you objects are you seeing in your map. All objects in a map a clickebled.',
        photoUrl:'../../public/pictures/mapapp.png',
        projectCode:'https://github.com/Kost90/test-task',
        projectUrl:'https://test-task-liard-mu.vercel.app/',
        type:'react-app',
        logoUrld:'../../public/svg/react-logo.svg',
    },
    {
        id:8,
        name:'Resume generator',
        description:'Full stack React web application, you can create a CV with ChatGPT API.',
        photoUrl:'../../public/pictures/resume-generator.png',
        projectCode:'https://github.com/Kost90/resumeGenerator',
        projectUrl:'https://main--reliable-souffle-132785.netlify.app/',
        type:'react-app',
        logoUrld:'../../public/svg/react-logo.svg',
    },
    {
        id:9,
        name:'TODO APP',
        description:'TODO app in html,css and javascript. You can add task, edit task and delete task. All information about your tasks saving in local storage of browser.',
        photoUrl:'../../public/pictures/to-do-app.png',
        projectCode:'https://github.com/Kost90/to-do-list',
        projectUrl:'https://kost90.github.io/to-do-list/',
        type:'js',
        logoUrld:'../../public/svg/logo-javascript.svg',
    },
]

module.exports = projects
  